config/routes.rb
Congressconnect::Application.routes.draw do
  resources :district_lookups
  resources :calls

  root :to => "district_lookups#new"

end

app/models/district_lookup.rb
class DistrictLookup
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :street, :postal_code

  validates_presence_of :street, :postal_code

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def new
    request.format = :twiml

    respond_to do | format |
      format.twiml
    end
  end
end

app/controllers/district_lookups_controller.rb
class DistrictLookupsController < ApplicationController
  def new
    @district_lookup = DistrictLookup.new
  end

  def create
    @district_lookup = DistrictLookup.new params[:district_lookup]
    if @district_lookup.valid?
      @district  = Sunlight::District.get(:address => "#{@district_lookup.street} #{@district_lookup.postal_code}" )
      @legislators = Sunlight::Legislator.all_in_district @district

      @capability = Twilio::Util::Capability.new(ACCOUNT_SID, AUTH_TOKEN)
      @capability.allow_client_outgoing(TWILIO_APPLICATION_ID)
      

      render :action => 'show'
    else
      render :action => 'new'
    end
  end

  def index
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calls/new.twiml.haml
%Response
  %Dial{:callerId => '(518) 207-6768'}
    %Number
      = params[:number]

app/views/district_lookups/_call_to_action.html.haml
%p
  It's outrageous--right-wing factions in Congress are willing to let America go into default and to put our entire economy at risk in order to get big cuts to Social Security and Medicare--all without ending the tax breaks that put us in debt in the first place.
%p
  The negotiations are coming down to the wire and members of Congress from both parties need to hear from constituents who oppose the cuts and don't want to see our nation default.
%p
  %b
    Enter your address and you'll be able to make a call right now, via your computer, to your Representative and Senators to tell them "I don't want America to default and I oppose any cuts Social Security, Medicare, or Medicaid."

app/views/district_lookups/_legislator.html.haml
.legislator
  .bio
    .name
      = leg.firstname
      = leg.lastname
    .phone
      = leg.phone
  .call
    %button{:class =>"call",  :onclick=>"call('#{leg.phone}');"}
  .clear

app/views/district_lookups/new.html.haml
.main-content
  = render :partial => 'call_to_action'


.details-column

  :coffeescript
    $(document).ready ->
      jQuery('#new_district_lookup').formHints();


  %h3
    Call Your Representatives

  = @district_lookup.errors.on(:base)

  = form_for @district_lookup do |form|
    .input-box
      .input-left
      = form.text_field :street, :required => false, :title => 'Home Street Address'
      .input-right
    .clear


    .input-box
      .input-left
      = form.text_field :postal_code, :required => false, :title => 'Zip Code'
      .input-right
    .left
      = form.submit 'Lookup'

app/views/district_lookups/show.html.haml
- if @legislators.collect{|key, value| value}.compact.any?
  .main-content
    = render :partial => 'call_to_action'


  .details-column
    .top-box
      .instructions
        We'll use the microphone in your computer to connect you
        with your member of congress. Make sure your volume is turned
        up and then press Call.
      .status{:style => "display:none;"}
        .log{:id => 'log'}
          Loading Pigeons...
        %button{:class=>"hangup", :onclick=>"hangup();"}

    .legislators
      - @legislators.each do |key, value|
        = render :partial => 'legislator', :locals => {:leg => value, :kind => key} if value
      = link_to "Lookup Another Address", new_district_lookup_path, {:class => 'minimalist'}
      %br
      = link_to "Running into problems?", "mailto:bugs@rebuildthedream.com", {:class => 'minimalist'}
    :javascript
      $(document).ready(function() {
        try {
          Twilio.Device.setup("#{@capability.generate}");
        } catch (err) {
          alert("You need Flash installed and enabled to use this site.");
        }
      });

      Twilio.Device.ready(function (device) {
        $("#log").text("Ready");
      });

      Twilio.Device.error(function (error) {
        $("#log").text("Error: " + error.message);
      });

      Twilio.Device.connect(function (conn) {
        $("#log").text("Successfully established call");
      });

      Twilio.Device.disconnect(function (conn) {
        $("#log").text("Call ended");
      });

      var connection;
      function call(number) {
        params =  { "number" : number };
        $('.instructions').hide();
        $('.status').show();
        connection = Twilio.Device.connect(params);
      }

      function hangup() {
        Twilio.Device.disconnectAll();
        connection = null;
        $('.instructions').show();
        $('.status').hide();
      }

      $(document).keypress(function(key) {
        if(key.which >= 48 && key.which <=57 && connection) {
          connection.sendDigits(String.fromCharCode(key.charCode));
        }

      });


- else
  This campaign is not available here.

  = link_to "Try Another Address", new_district_lookup_path

app/views/layouts/_signup.html.erb
 <form method="POST" action="http://www.moveon.org/petition/process_petition.html" class="email-signup">

  <input type="hidden" value="1059" name="petition_id">
  <input type="hidden" value="1" name="posted">
  <input type="hidden" value="1" name="dont_send_confirm">
  <input type="hidden" name="track_referrer">
  <input type="hidden" value="https://civ.moveon.org/donatec4/rebuild_donate.html?rc=callforthedream" name="redirect_url">
  <input type="hidden" value=" " name="name">

  <div class="email-field input-box">
    <div class="input-left"></div>
    <input type="text" onfocus="inputFocus(this,'Email Address')" onblur="inputBlur(this,'Email Address')" class="inline-label" value="Email Address" name="email">
    <div class="input-right input-end"></div>
  </div>

  <div class="zip-field input-box input-inline">
    <div class="input-left"></div>
    <input type="text" onfocus="inputFocus(this,'Zip Code')" onblur="inputBlur(this,'Zip Code')" class="inline-label" value="Zip Code" name="zip">
    <div class="input-right"></div>
  </div>

  <input type="submit" value="Join" class="submit-field">

  <div style="clear: both;"></div>

</form>


<script>
function inputBlur(field,text) {
  if (field.value=='') {
    field.value=text;
    field.style.color="#888888";
  }
}

function inputFocus(field,text) {
  if (field.value==text) {
    field.value='';
  }
  field.style.color="#000000";
}
</script>

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title
      = 'Call For The Dream'

    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if lt IE 8]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'

    %link{:rel=>"shortcut icon", :href=>"/images/favicon.ico", :type=>"image/x-icon"}

    %script{:type => "text/javascript", :src => "https://static.twilio.com/libs/twiliojs/1.0/twilio.min.js"}

    = javascript_include_tag :defaults
    = csrf_meta_tag
    = javascript_include_tag 'underscore-min', 'jquery-formhints'

    %meta{:property => "og:title",       :content => "Call For The American Dream"}
    %meta{:property => "og:image",       :content => image_path('rebuild.png')}
    %meta{:property => "og:description", :content =>"Make a call right now, via your computer, to your Congresspeople to tell them \"I don't want America to default and I oppose any cuts Social Security, Medicare, or Medicaid.\""}
    %meta{:property => "og:group",       :content => "cause" }

    :plain
      <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-24813972-1']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

      </script>

  %body{:class => 'bp'}
    .container
      .header-container
        .header
          = link_to image_tag('logo.png'), '/'
          .share
            :coffeescript
              $(document).ready ->
                jQuery('#fb-share').bind 'click', (event) =>
                  window.open('http://www.facebook.com/sharer.php?u=#{CGI.escape('http://callforthedream.com/')}','sharer','toolbar=0,status=0,width=626,height=436');

                jQuery('#twitter-share').bind 'click', (event) =>
                  window.open('http://twitter.com/share?url=#{CGI.escape('http://callforthedream.com/')}&text=#{CGI.escape('Call Congress for free from your computer: "No Default, No Cuts to Social Sec., Medicare, Medicaid" via @rebuilddream')}','sharer','toolbar=0,status=0,width=626,height=436');


            .fb-share{ :id => 'fb-share'}
            .twitter-share{:id => 'twitter-share'}
          -#.signup
          -#  = render :partial => 'layouts/signup'
        .clear

        .header-strip
      .content
        .content-wrapper
          .messages
            - flash.each do |key, msg|
              %div{'class' => key}
                = msg
          = yield
      .footer
        .footer-wrapper
          .powered
            Powered By
          .logos
            = link_to image_tag('rebuild.gif'), 'http://www.rebuildthedream.com/'
            = link_to image_tag('rewire.png'), 'http://www.rewirelabs.com/'
            = link_to image_tag('twilio.png'), 'http://www.twilio.com/'

          .privacy{:style => 'text-align:center; margin:0px auto 10px'}
            = link_to 'Privacy policy', 'http://www.rebuildthedream.com/privacy.php', :class => 'minimalist'